name: Fetch keys

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl 'https://github.com/${{ github.repository_owner }}.keys' -o authorized_keys
          git config user.name '${{ github.event.repository.owner.name }}'
          git config user.email '${{ github.event.repository.owner.email }}'
          git add .
          git commit -m "Update to latest keys"
          git push
